### GET request to example server
GET localhost:8000/teacher?email=adrian@gmail.com

###
POST localhost:8000/teacher
Content-Type: application/json

{
  "name" :"Adrian1",
  "fullname":"Adrian Alejandro1",
  "username":"adrian1",
  "specialty" : "programming1",
  "contract_type":"undefined1",
  "experience" :"11",
  "email":"adrian11@gmail.com",
  "password":"12341"
}