


### GET request to example server
GET localhost:8000/teacher?email=adrian@gmail.com

###

GET localhost:8000/teacher
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiJhZHJpYW4iLCJ0eXBlIjoidGVhY2hlciIsImV4cCI6MTczNTc4NDUyOH0.cYVpibpPGZ4Wq-aDPnJjOGckfO5iaMoYWD8Alpd-MpI



###
POST localhost:8000/teacher
Content-Type: application/json

{
  "name" :"Adrian1",
  "fullname":"Adrian Alejandro1",
  "username":"adrian1",
  "specialty" : "programming1",
  "contract_type":"undefined1",
  "experience" :"11",
  "email":"adrian11@gmail.com",
  "password":"12341"
}

###
DELETE localhost:8000/teacher/bed42a7e-c6e2-45dc-b0fc-e54d7d2a64ee

###
PATCH localhost:8000/teacher/054ddf7b-5d80-4636-b02c-a49180227319
Content-Type: application/json

{
  "contract_type":"Parcial"
}