"""add note_average column to Student Table

Revision ID: 0571b32e19e5
Revises: af058660eb0d
Create Date: 2025-01-05 14:17:54.401694

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0571b32e19e5'
down_revision: Union[str, None] = 'af058660eb0d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('student', sa.Column('average_note', sa.Double(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('student', 'average_note')
    # ### end Alembic commands ###
