"""Add roles to UserTable

Revision ID: 0769a22dbce8
Revises: b7bb9d53e8bf
Create Date: 2025-02-01 20:26:04.790060

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0769a22dbce8'
down_revision: Union[str, None] = 'b7bb9d53e8bf'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('roles', sa.ARRAY(sa.Enum('ADMIN', 'SECRETARY', 'TEACHER', 'DEAN', 'STUDENT', name='roles')), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'roles')
    # ### end Alembic commands ###
