"""Add teacher requests

Revision ID: 08ab7f208c9a
Revises: df72c6c97712
Create Date: 2025-01-18 12:10:37.521992

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '08ab7f208c9a'
down_revision: Union[str, None] = 'df72c6c97712'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('teacher_request_classroom',
    sa.Column('teacher_id', sa.UUID(), nullable=False),
    sa.Column('classroom_id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['classroom_id'], ['classroom.entity_id'], ),
    sa.ForeignKeyConstraint(['teacher_id'], ['teacher.id'], ),
    sa.PrimaryKeyConstraint('teacher_id', 'classroom_id')
    )
    op.create_table('teacher_request_mean',
    sa.Column('teacher_id', sa.UUID(), nullable=False),
    sa.Column('mean_id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['mean_id'], ['mean.entity_id'], ),
    sa.ForeignKeyConstraint(['teacher_id'], ['teacher.id'], ),
    sa.PrimaryKeyConstraint('teacher_id', 'mean_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('teacher_request_mean')
    op.drop_table('teacher_request_classroom')
    # ### end Alembic commands ###
