"""Fix course student relationship 4.0 

Revision ID: 08bcb1771228
Revises: 7d8220b4b172
Create Date: 2025-01-27 16:10:26.342732

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '08bcb1771228'
down_revision: Union[str, None] = '7d8220b4b172'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('student', sa.Column('course_year', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('student', 'course_year')
    # ### end Alembic commands ###
