"""added relationship new

Revision ID: 0964293fb2bb
Revises: 96efd5042c0f
Create Date: 2025-01-06 20:23:12.165685

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0964293fb2bb'
down_revision: Union[str, None] = '96efd5042c0f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('subject', sa.Column('classroom_id', sa.UUID(), nullable=False))
    op.create_foreign_key(None, 'subject', 'classroom', ['classroom_id'], ['entity_id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'subject', type_='foreignkey')
    op.drop_column('subject', 'classroom_id')
    # ### end Alembic commands ###
