"""Add name and lastname to UserTable

Revision ID: 09fd02bc13fd
Revises: f87b4f96f63d
Create Date: 2025-01-30 13:24:16.082805

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '09fd02bc13fd'
down_revision: Union[str, None] = 'f87b4f96f63d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('administrator', 'name')
    op.drop_column('secretary', 'name')
    op.drop_column('student', 'name')
    op.drop_column('teacher', 'name')
    op.drop_column('teacher', 'fullname')
    op.add_column('user', sa.Column('name', sa.String(), nullable=True))
    op.add_column('user', sa.Column('lastname', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'lastname')
    op.drop_column('user', 'name')
    op.add_column('teacher', sa.Column('fullname', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('teacher', sa.Column('name', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('student', sa.Column('name', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('secretary', sa.Column('name', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('administrator', sa.Column('name', sa.VARCHAR(), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
