"""Add course subject relationship 2.0 

Revision ID: 13b3b6a09952
Revises: 81f0f0cafa24
Create Date: 2025-01-27 16:56:03.871481

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '13b3b6a09952'
down_revision: Union[str, None] = '81f0f0cafa24'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
