"""hola4

Revision ID: 15e354ea41fd
Revises: 125c3bbc4cb2
Create Date: 2025-02-02 12:48:54.113248

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '15e354ea41fd'
down_revision: Union[str, None] = '125c3bbc4cb2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('teacher_id_fkey', 'teacher', type_='foreignkey')
    op.create_foreign_key(None, 'teacher', 'user', ['id'], ['entity_id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'teacher', type_='foreignkey')
    op.create_foreign_key('teacher_id_fkey', 'teacher', 'user', ['id'], ['entity_id'], ondelete='CASCADE')
    # ### end Alembic commands ###
