"""hola13

Revision ID: ce7c5a26665c
Revises: 
Create Date: 2025-02-03 02:02:19.914518

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import uuid
from sqlalchemy.dialects.postgresql import UUID

# revision identifiers, used by Alembic.
revision: str = 'ce7c5a26665c'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade():
    # Step 1: Drop the existing primary key constraint
    op.drop_constraint('teacher_note_pkey', 'teacher_note', type_='primary')

    # Step 3: Recreate the primary key constraint without 'student_id'
    op.create_primary_key('teacher_note_pkey', 'teacher_note', ['entity_id', 'teacher_id', 'subject_id'])


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'teacher_note', type_='foreignkey')
    op.create_foreign_key('teacher_note_student_id_fkey', 'teacher_note', 'student', ['student_id'], ['id'])
    op.alter_column('teacher_note', 'student_id',
               existing_type=sa.UUID(),
               nullable=False)
    # ### end Alembic commands ###
