"""change course foreign key in Student table

Revision ID: 24b4a9265205
Revises: be33acd7ea99
Create Date: 2025-01-27 15:46:09.713048

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '24b4a9265205'
down_revision: Union[str, None] = 'be33acd7ea99'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('student_course_id_fkey', 'student', type_='foreignkey')
    op.drop_column('student', 'course_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('student', sa.Column('course_id', sa.UUID(), autoincrement=False, nullable=False))
    op.create_foreign_key('student_course_id_fkey', 'student', 'course', ['course_id'], ['entity_id'])
    # ### end Alembic commands ###
