"""delete change config

Revision ID: 3bcb3588e8da
Revises: 674bc0bb23ab
Create Date: 2025-01-28 15:18:55.243335

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3bcb3588e8da'
down_revision: Union[str, None] = '674bc0bb23ab'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('student_course_id_fkey', 'student', type_='foreignkey')
    op.create_foreign_key(None, 'student', 'course', ['course_id'], ['entity_id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'student', type_='foreignkey')
    op.create_foreign_key('student_course_id_fkey', 'student', 'course', ['course_id'], ['entity_id'])
    # ### end Alembic commands ###
