"""hola2

Revision ID: 58060cf6c362
Revises: 0387ac9783d8
Create Date: 2025-02-02 12:44:10.208413

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '58060cf6c362'
down_revision: Union[str, None] = '0387ac9783d8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('dean_id_fkey', 'dean', type_='foreignkey')
    op.create_foreign_key(None, 'dean', 'teacher', ['id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'dean', type_='foreignkey')
    op.create_foreign_key('dean_id_fkey', 'dean', 'teacher', ['id'], ['id'])
    # ### end Alembic commands ###
