"""add note_average column to Teacher Table

Revision ID: 58b806a1636e
Revises: 0571b32e19e5
Create Date: 2025-01-05 15:29:03.447620

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '58b806a1636e'
down_revision: Union[str, None] = '0571b32e19e5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('teacher', sa.Column('average_valoration', sa.Double(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('teacher', 'average_valoration')
    # ### end Alembic commands ###
