"""Change abscence table

Revision ID: 674bc0bb23ab
Revises: 7a42bbfaecf6
Create Date: 2025-01-28 11:08:31.728175

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '674bc0bb23ab'
down_revision: Union[str, None] = '7a42bbfaecf6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('absence', sa.Column('date', sa.DateTime(), nullable=False))
    op.drop_constraint('absence_course_id_fkey', 'absence', type_='foreignkey')
    op.drop_column('absence', 'absences')
    op.drop_column('absence', 'course_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('absence', sa.Column('course_id', sa.UUID(), autoincrement=False, nullable=False))
    op.add_column('absence', sa.Column('absences', sa.INTEGER(), autoincrement=False, nullable=True))
    op.create_foreign_key('absence_course_id_fkey', 'absence', 'course', ['course_id'], ['entity_id'])
    op.drop_column('absence', 'date')
    # ### end Alembic commands ###
