"""Add name and lastname to UserTable2

Revision ID: 6b861af67773
Revises: 8c071f6ce79d
Create Date: 2025-02-01 11:18:58.892137

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6b861af67773'
down_revision: Union[str, None] = '8c071f6ce79d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
