"""Fix course student relationship 2.0 

Revision ID: 6d3e855faa9e
Revises: cfbe4236c99a
Create Date: 2025-01-27 15:58:34.255288

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6d3e855faa9e'
down_revision: Union[str, None] = 'cfbe4236c99a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
