"""Delete course_year column from subject and student

Revision ID: 7a42bbfaecf6
Revises: e08691a0f603
Create Date: 2025-01-28 00:20:21.805730

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7a42bbfaecf6'
down_revision: Union[str, None] = 'e08691a0f603'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('student', 'course_year')
    op.drop_column('subject', 'course_year')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('subject', sa.Column('course_year', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('student', sa.Column('course_year', sa.INTEGER(), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
