"""Add events

Revision ID: 7ab23ad27c4c
Revises: 8075a1cf7346
Create Date: 2025-02-01 12:16:20.875701

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7ab23ad27c4c'
down_revision: Union[str, None] = '8075a1cf7346'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('valoration_period', sa.Column('open', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('valoration_period', 'open')
    # ### end Alembic commands ###
