"""Fix course student relationship 3.0 

Revision ID: 7d8220b4b172
Revises: 6d3e855faa9e
Create Date: 2025-01-27 15:59:41.749754

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7d8220b4b172'
down_revision: Union[str, None] = '6d3e855faa9e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
