"""hola22

Revision ID: 7e9f64973124
Revises: 645850074eb1
Create Date: 2025-02-02 19:53:17.802686

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7e9f64973124'
down_revision: Union[str, None] = '645850074eb1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('administrator_id_fkey', 'administrator', type_='foreignkey')
    op.create_foreign_key(None, 'administrator', 'user', ['id'], ['entity_id'])
    op.drop_constraint('dean_id_fkey', 'dean', type_='foreignkey')
    op.create_foreign_key(None, 'dean', 'teacher', ['id'], ['id'])
    op.drop_constraint('teacher_id_fkey', 'teacher', type_='foreignkey')
    op.create_foreign_key(None, 'teacher', 'user', ['id'], ['entity_id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'teacher', type_='foreignkey')
    op.create_foreign_key('teacher_id_fkey', 'teacher', 'user', ['id'], ['entity_id'], ondelete='CASCADE')
    op.drop_constraint(None, 'dean', type_='foreignkey')
    op.create_foreign_key('dean_id_fkey', 'dean', 'teacher', ['id'], ['id'], ondelete='CASCADE')
    op.drop_constraint(None, 'administrator', type_='foreignkey')
    op.create_foreign_key('administrator_id_fkey', 'administrator', 'user', ['id'], ['entity_id'], ondelete='CASCADE')
    # ### end Alembic commands ###
