"""Add update average note trigger7.0

Revision ID: 8075a1cf7346
Revises: d487a61c00a8
Create Date: 2025-02-01 11:46:03.463597

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8075a1cf7346'
down_revision: Union[str, None] = 'd487a61c00a8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
