"""Add to_be_replaced column to MeanTablew

Revision ID: 81037cc6277f
Revises: d492ca93fc23
Create Date: 2025-01-21 15:34:20.091351

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '81037cc6277f'
down_revision: Union[str, None] = 'd492ca93fc23'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('mean', sa.Column('to_be_replaced', sa.Boolean(), default=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('mean', 'to_be_replaced')
    # ### end Alembic commands ###
