"""Add course subject relationship

Revision ID: 81f0f0cafa24
Revises: 99a94611980d
Create Date: 2025-01-27 16:51:13.902740

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '81f0f0cafa24'
down_revision: Union[str, None] = '99a94611980d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('subject', sa.Column('course_year', sa.Integer(), nullable=True))
    op.add_column('subject', sa.Column('course_id', sa.UUID(), nullable=False))
    op.create_foreign_key(None, 'subject', 'course', ['course_id'], ['entity_id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'subject', type_='foreignkey')
    op.drop_column('subject', 'course_id')
    op.drop_column('subject', 'course_year')
    # ### end Alembic commands ###
