"""Add name and lastname to UserTable2

Revision ID: 8c071f6ce79d
Revises: da16984a2251
Create Date: 2025-02-01 11:18:13.086904

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8c071f6ce79d'
down_revision: Union[str, None] = 'da16984a2251'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
