"""Fix course student relationship 6.0 

Revision ID: 99a94611980d
Revises: 6a3e01666be6
Create Date: 2025-01-27 16:17:46.249849

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '99a94611980d'
down_revision: Union[str, None] = '6a3e01666be6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('student', sa.Column('course_id', sa.UUID(), nullable=False))
    op.create_foreign_key(None, 'student', 'course', ['course_id'], ['entity_id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'student', type_='foreignkey')
    op.drop_column('student', 'course_id')
    # ### end Alembic commands ###
