"""added relationship

Revision ID: af058660eb0d
Revises: 948a7cf09b99
Create Date: 2024-12-30 15:15:31.294371

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'af058660eb0d'
down_revision: Union[str, None] = '948a7cf09b99'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('technological_mean', sa.Column('classroom_id', sa.UUID(), nullable=False))
    op.create_foreign_key(None, 'technological_mean', 'classroom', ['classroom_id'], ['entity_id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'technological_mean', type_='foreignkey')
    op.drop_column('technological_mean', 'classroom_id')
    # ### end Alembic commands ###
