"""Delete date id column form maintenance

Revision ID: afe436e8bf4a
Revises: 3bcb3588e8da
Create Date: 2025-01-28 20:19:11.708283

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'afe436e8bf4a'
down_revision: Union[str, None] = '3bcb3588e8da'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('mean_maintenance_table_date_id_fkey', 'mean_maintenance_table', type_='foreignkey')
    op.drop_column('mean_maintenance_table', 'date_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('mean_maintenance_table', sa.Column('date_id', sa.UUID(), autoincrement=False, nullable=False))
    op.create_foreign_key('mean_maintenance_table_date_id_fkey', 'mean_maintenance_table', 'my_date', ['date_id'], ['entity_id'])
    # ### end Alembic commands ###
