"""Add number column to Classroom Table

Revision ID: b7bb9d53e8bf
Revises: 0df1f564288a
Create Date: 2025-02-01 14:31:26.315413

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b7bb9d53e8bf'
down_revision: Union[str, None] = '0df1f564288a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('classroom', sa.Column('number', sa.Integer(), nullable=True))
    op.create_unique_constraint(None, 'classroom', ['number'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'classroom', type_='unique')
    op.drop_column('classroom', 'number')
    # ### end Alembic commands ###
