"""Change CourseTable structure 

Revision ID: be33acd7ea99
Revises: af262b1cedfb
Create Date: 2025-01-27 15:29:35.502144

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'be33acd7ea99'
down_revision: Union[str, None] = 'af262b1cedfb'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('course', sa.Column('year', sa.Integer(), nullable=False))
    op.create_unique_constraint(None, 'course', ['year'])
    op.drop_column('course', 'end_year')
    op.drop_column('course', 'start_year')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('course', sa.Column('start_year', sa.INTEGER(), autoincrement=False, nullable=False))
    op.add_column('course', sa.Column('end_year', sa.INTEGER(), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'course', type_='unique')
    op.drop_column('course', 'year')
    # ### end Alembic commands ###
