"""Add finished column to Maintenance

Revision ID: d17fff26596e
Revises: 09fd02bc13fd
Create Date: 2025-01-30 17:10:21.728839

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd17fff26596e'
down_revision: Union[str, None] = '09fd02bc13fd'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('mean_maintenance_table', sa.Column('finished', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('mean_maintenance_table', 'finished')
    # ### end Alembic commands ###
