"""hola11

Revision ID: d3c967aa8576
Revises: b90f5688685d
Create Date: 2025-02-02 14:44:12.518324

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd3c967aa8576'
down_revision: Union[str, None] = 'b90f5688685d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('mean', 'classroom_id',
               existing_type=sa.UUID(),
               nullable=True)
    op.alter_column('subject', 'classroom_id',
               existing_type=sa.UUID(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('subject', 'classroom_id',
               existing_type=sa.UUID(),
               nullable=False)
    op.alter_column('mean', 'classroom_id',
               existing_type=sa.UUID(),
               nullable=False)
    # ### end Alembic commands ###
