"""Add teacher requests foreign keys 3

Revision ID: d492ca93fc23
Revises: dded3ccc966b
Create Date: 2025-01-18 12:47:51.506222

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd492ca93fc23'
down_revision: Union[str, None] = 'dded3ccc966b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
