"""change classroom_id to MeanTable

Revision ID: d7a681f2aa14
Revises: 73f480f314c8
Create Date: 2025-01-16 14:42:39.686366

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd7a681f2aa14'
down_revision: Union[str, None] = '73f480f314c8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('mean', sa.Column('classroom_id', sa.UUID(), nullable=False))
    op.create_foreign_key(None, 'mean', 'classroom', ['classroom_id'], ['entity_id'])
    op.drop_constraint('technological_mean_classroom_id_fkey', 'technological_mean', type_='foreignkey')
    op.drop_column('technological_mean', 'classroom_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('technological_mean', sa.Column('classroom_id', sa.UUID(), autoincrement=False, nullable=False))
    op.create_foreign_key('technological_mean_classroom_id_fkey', 'technological_mean', 'classroom', ['classroom_id'], ['entity_id'])
    op.drop_constraint(None, 'mean', type_='foreignkey')
    op.drop_column('mean', 'classroom_id')
    # ### end Alembic commands ###
