"""Add teacher requests foreign keys 2

Revision ID: dded3ccc966b
Revises: b999dbf704f5
Create Date: 2025-01-18 12:34:54.348129

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'dded3ccc966b'
down_revision: Union[str, None] = 'b999dbf704f5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
