"""Add last_modified_by column to StudentNote

Revision ID: df72c6c97712
Revises: d7a681f2aa14
Create Date: 2025-01-17 12:22:41.837495

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'df72c6c97712'
down_revision: Union[str, None] = 'd7a681f2aa14'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('student_note', sa.Column('last_modified_by', sa.UUID(), nullable=False))
    op.create_foreign_key(None, 'student_note', 'user', ['last_modified_by'], ['entity_id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'student_note', type_='foreignkey')
    op.drop_column('student_note', 'last_modified_by')
    # ### end Alembic commands ###
