"""Change delete conditions in subject and course relationships

Revision ID: e08691a0f603
Revises: 13b3b6a09952
Create Date: 2025-01-28 00:04:03.308935

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e08691a0f603'
down_revision: Union[str, None] = '13b3b6a09952'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
