"""hola20

Revision ID: eea7e2899ba2
Revises: c067f588ce76
Create Date: 2025-02-02 19:14:28.508082

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'eea7e2899ba2'
down_revision: Union[str, None] = 'c067f588ce76'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('teacher_subject_subject_id_fkey', 'teacher_subject', type_='foreignkey')
    op.drop_constraint('teacher_subject_teacher_id_fkey', 'teacher_subject', type_='foreignkey')
    op.create_foreign_key(None, 'teacher_subject', 'teacher', ['teacher_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(None, 'teacher_subject', 'subject', ['subject_id'], ['entity_id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'teacher_subject', type_='foreignkey')
    op.drop_constraint(None, 'teacher_subject', type_='foreignkey')
    op.create_foreign_key('teacher_subject_teacher_id_fkey', 'teacher_subject', 'teacher', ['teacher_id'], ['id'])
    op.create_foreign_key('teacher_subject_subject_id_fkey', 'teacher_subject', 'subject', ['subject_id'], ['entity_id'])
    # ### end Alembic commands ###
