/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import {useGLTF, useAnimations} from '@react-three/drei'
import {useEffect, useRef, useState} from "react";
import gsap from "gsap";

export default function Universitario(props) {
    const group = useRef()
    const {nodes, materials, animations} = useGLTF('/sombrero_universitario.glb')
    const {actions} = useAnimations(animations, group)
    const [rotationValue, setRotationValue] = useState(0);
    useEffect(() => {
        gsap.to({}, {
            duration: 1,
            repeat: -1,
            onUpdate: () => {
                setRotationValue(prevValue => (prevValue+0.01)%3.14
                );
            }
        });
    }, []);
    return (
        <group ref={group} {...props} dispose={null}>
            <group name="Scene" rotation={[Math.PI/10, rotationValue, 0]}>
                <mesh
                    name="Círculo"
                    castShadow
                    receiveShadow
                    geometry={nodes.Círculo.geometry}
                    material={materials.Material}
                />
                <mesh
                    name="Cubo"
                    castShadow
                    receiveShadow
                    geometry={nodes.Cubo.geometry}
                    material={materials.Material}
                    position={[0, -0.781, 0]}
                    scale={1.364}
                />
            </group>
        </group>
    )
}

useGLTF.preload('/sombrero_universitario.glb')

